config/routes.rb
Rails.application.routes.draw do


  # get 'works/new'
  # get 'session/new'
  root :to => 'pages#home'
  resources :users
  resources :works
  resources :rateworks
  resources :contracts
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/search' => 'pages#search'
  # get 'contracts/new'
  post '/ranks/add' => 'ranks#create'

  get '/error/:msg' => 'pages#error'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  # get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contract.rb
class Contract < ApplicationRecord
  # belongs_to :user, :optional => true
  belongs_to :seller, class_name: "User", :foreign_key => "seller_id" ,:optional => true
  belongs_to :buyer, class_name: "User",:foreign_key => "user_id" ,:optional => true

  # validates :contract_from, presence: true
  # validate :must_have_valid_future_date
  #
  # private
  # def must_have_valid_future_date
  #   if contract_from.present?
  #       if contract_from < Date.today
  #           errors.add(:contract_from, "can't be in the past")
  #       end
  #   end
  # end

end

app/controllers/contracts_controller.rb
# require 'pry'
class ContractsController < ApplicationController
  def new
    if @current_user.admin == "Buyer"

    @contract = Contract.new
    if session[:work]!= nil && session[:work]["user_id"] != nil
      @seller_id = session[:work]["user_id"].to_i
    else
      @seller_id = 0
    end
    @users = User.where.not(:admin => 'Buyer')
  else
    @msg = "Access Denied"
    redirect_to "/error/#{@msg}"
  end
  end
  def index
    session[:work] = nil
    # @contracts = Contract.where(:user_id => @current_user.id)
    @user = User.find_by :id => @current_user.id
    if @current_user.admin == "Buyer"
    @contracts = @user.buyer_contracts
    else
    @contracts = @user.seller_contracts
    end
    # binding.pry
  end
  def show
    @user = User.find_by :id => @current_user.id
    # binding.pry
    if @current_user.admin == "Buyer"
      @contract = @user.buyer_contracts.where(:id => params[:id])
    else
      @contract = @user.seller_contracts.where(:id => params[:id])
    end

  end
  def edit
    @users = User.where.not(:admin => 'Buyer')
    @contract = Contract.find params[:id]
    if @current_user.admin != "Buyer"
      @disable = true
    elsif @current_user.admin == "Buyer" && @contract.status != "New"
      @disable = true
    else
      @disable = false
    end
  end
  def create
    contract = Contract.new contracts_params
    contract.user_id = @current_user.id
    # binding.pry

    # contract.seller_id = session[:work]["user_id"]
    contract.save
    redirect_to contracts_path
  end

  def update
    contract = Contract.find params[:id]
    contract.update contracts_params
    redirect_to contract
  end
  def destroy
    contract = Contract.find params[:id]
    contract.destroy
    redirect_to contracts_path
  end
  def contracts_params
    params.require(:contract).permit(:title,:user_id,:seller_id,:description,:contract_from,:contract_to,:status,:amount,:services)
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_for @contract do |f| %>

    <% if @contract.persisted? %>
        <% if @contract.seller_id == @current_user.id && @contract.status == "New" %>
          <% @statusarr = ['Signed by Seller']%>
        <% else %>
          <% @statusarr = ['New','Approved','Reject','Signed by Seller']%>
        <% end %>
      <% @seller_id = @contract.seller_id %>
    <% else %>
      <% @statusarr = ['New']%>
    <% end %>
<!-- <div class="col-md-8 col-md-offset-2"> -->
<div class="row">
  <div class="col-4 offset-md-3">
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, :required => true, :autofocus => true,:id => "txttitle", :readonly => @disable, :class => "form-control txt" %>
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      <%= f.label :seller_id, "Designer" %>
      <%= f.select :seller_id, options_for_select(@users.collect{|user| [user.name, user.id]}, @seller_id),
      :prompt => "Select One", :readonly => @disable,:class => 'form-control drp'%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-4 offset-md-3">
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, :required => true,:id => "txtdescription",:readonly => @disable, :class => "form-control txtarea" %>
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      <%= f.label :services, "Services" %>
      <%= f.text_area :services, :required => true ,:readonly => @disable, :class => "form-control txtarea"%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-4 offset-md-3">
    <div class="form-group">
      <%= f.label :contract_from, "Start date"%>
      <%= f.date_field :contract_from, :required => true,:readonly => @disable, :class => "form-control txt" %>
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      <%= f.label :amount, "Amount" %>
      <%= f.text_field :amount ,:type => "Number", :required => true,:readonly => @disable,:class => "form-control txt" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-4 offset-md-3">
    <div class="form-group">
      <%= f.label :contract_to, "End date" %>
      <%= f.date_field :contract_to, :required => true ,:readonly => @disable,:class => "form-control txt"%>
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      <%= f.label :status %>
      <% @selectoptions = { :class => "form-control txt" }%>
      <% if @contract.status == "Approved" %>
      <% @statusdisabled = true; @selectoptions[:disabled] = true  %>
      <% end %>
      <%= f.select :status, options_for_select( @statusarr,
      :selected => @contract.status),
      {:required => true, :class => 'select'}, @selectoptions %>
      <%= hidden_field "hidden", :id => "valdisable", :value => @disable %>
    </div>
  </div>
  <div class="col-4 offset-md-3">
    <%= f.submit "Save", :id => "btncontract",:class => "btn btn-primary m-b10", :disabled => @statusdisabled %>
  </div>
</div>
<% end %>
<!-- </div> -->

app/views/contracts/edit.html.erb
<div class="workcontainer">
<h2 class="offset-md-5">Edit Contract</h2>
  <%= render :partial => 'form' %>
</div>

app/views/contracts/index.html.erb
<h2>
  Contracts
    <% if @current_user.admin == "Buyer" %>
    <%= "Generated by Me" %>
    <% else %>
    <%= "Assigned to Me" %>
    <% end %>
</h2>

<% if @current_user.admin == "Buyer" %>
  <%= link_to "Create Contract", new_contract_path,:class => "btn btn-primary"  %>
<% end %>
<table>
  <th>Description</th><th>Created By</th><th>Designer Name</th><th>Designer Contact No</th><th>From</th><th>To</th><th>Status</th><th>Amount</th>
  <% @contracts.each do |contract| %>
  <tr>
  <td>
  <%= link_to contract.description, contract %>
  </td>
  <td>
    <%= contract.buyer.name %>
  </td>
  <td>
    <%= contract.seller.name %>
  </td>
  <td>
    <%= number_to_phone contract.seller.phone %>
  </td>
  <td>
    <%= contract.contract_from.strftime('%e %B, %Y') if contract.contract_from.present? %>
  </td>
  <td>
    <%= contract.contract_to.strftime('%e %B, %Y') if contract.contract_to.present? %>
  </td>
  <td>
    <%= contract.status %>
  </td>
  <td>
    <%= number_to_currency contract.amount %>
  </td>
  <% end %>
</tr>
</table>

app/views/contracts/new.html.erb
<div class="workcontainer">
<h2 class="centerdiv">Add Contract</h2>
  <%= render :partial => 'form' %>
</div>

app/views/contracts/show.html.erb
<div class="workcontainer">
  <div class="row">
    <div class="col-8 offset-md-2">
          <% @contract.each do |contract| %>
            <h2><%= contract.title %></h2>
            <p>This agreement effective from <%= contract.contract_from.strftime('%e %B, %Y') if contract.contract_from.present? %> till <%= contract.contract_to.strftime('%e %B, %Y') if contract.contract_to.present? %> between <%= contract.buyer.name %> and <%= contract.seller.name %></p>
            <h3>Services:</h3>
            <p><%= contract.services %></p>
            <p>Client agrees to pay a fee of <%= number_to_currency contract.amount if contract.amount.present? %> to the designer for the services outlined above.</p>
            <p><%= contract.description %></p>

            <%= link_to 'Edit', edit_contract_path(contract),:class => "btn btn-primary m-b10" %>
              <% if @current_user.admin == "Buyer" && contract.status == "New" %>
                  <%= link_to 'Delete', contract, :method => 'delete',:class => "btn btn-primary m-b10" %>
              <% end %>
          <% end %>
    </div>
  </div>
</div>