config/routes.rb
Rails.application.routes.draw do


  # get 'works/new'
  # get 'session/new'
  root :to => 'pages#home'
  resources :users
  resources :works
  resources :rateworks
  resources :contracts
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/search' => 'pages#search'
  # get 'contracts/new'
  post '/ranks/add' => 'ranks#create'

  get '/error/:msg' => 'pages#error'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  # get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/work.rb
class Work < ApplicationRecord
  include PgSearch
  pg_search_scope :search_full_text, against: %i(title description), using: { tsearch: {:prefix => true} }

  belongs_to :user, :optional => true
  has_many :rateworks
end

app/controllers/works_controller.rb
# require 'pry'

class WorksController < ApplicationController
  # before_action :fetch_access,:only => [:show]
  # before_action :check_for_usertype,:only => [:show]

  def new
    # session[:test] = "testing"
    # @test = session[:test]
    @work = Work.new
  end
  def index
    @works = Work.where(:user_id => @current_user.id)
  end
  def show
    @work = Work.find params[:id]
    session[:work] = @work
    @user = User.where(:id => @work.user_id).first
    @ratanlytics = Ratework.select("ranking").where(:work_id => params[:id]).group("ranking").count(:ranking)
    @rating = Ratework.where(:work_id => params[:id])

    # raise 'hell'
    @sum = 0
    @rating.each do |rating|
      @sum += rating.ranking
    end
    if @rating.any?
      @avgrating = (@sum / @rating.size).floor
    else
      @avgrating = 0
    end
    # raise 'hell'
    #@avgrating = 3#Ratework.group(:work_id).pluck("work_id, AVG(Round(ranking))").having(":work_id => #{params[:id]}")#pluck("AVG(Round(ranking))")
    # binding.pry
  end
  def edit
    @work = Work.find params[:id]
  end
  def create
    work = Work.new work_params
    work.user_id = @current_user.id
    if params[:image].present?
      req = Cloudinary::Uploader.upload(params[:image])
      work.image = req["public_id"]
    end
    if work.save
      redirect_to works_path
    else
      flash[:error_message] = "Error Unable to save your data."
    end
  end

  def update
    work = Work.find params[:id]
    if params[:image].present?
      req = Cloudinary::Uploader.upload(params[:image])
      work.image = req["public_id"]
    end
    work.update work_params
    redirect_to work
  end
  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end
  private
  def work_params
    params.require(:work).permit(:user_id,:image,:title,:description,:visit)
  end
  # private
  # def fetch_access
  #   if @current_user
  #
  #   else condition
  #   end
  #
  # end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<div class="row">
  <div class="col-6 offset-md-4">
    <% if flash[:error_message].present? %>
      <p><%= flash[:error_message] %></p>
    <% end %>

    <% if @work.persisted? %>
     <% @visit = @work.visit else @visit = 0 %>
    <% end %>


    <%= form_for @work do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, :required => true, :autofocus => true ,:class => "form-control txt" %>
      </div>
      <div class="form-group">
        <%= f.label :image, "Upload Image" %>
        <%= f.text_field :image, :class => "form-control txt" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "description" %>
        <%= f.text_area :description, :class => "form-control txtarea", :rows => 3 %>
      </div>
        <%= f.hidden_field :visit, :value => @visit %>
        <%= f.submit "Save", :class => "btn btn-primary m-b10" %>
    <% end %>
  </div>
</div>

app/views/works/edit.html.erb
<div class="workcontainer">
<h2 class="centerdiv">Add Work</h2>
<%= render :partial => 'form' %>
</div>

app/views/works/index.html.erb
<div class="workcontainer">
  <div class="row">
    <div class="col-8 offset-md-2">
          <h2>List of My Works</h2>
          <%= link_to "Add Work", new_work_path, :class => "btn btn-primary" %>

          <% if @works.any? %>
          <!-- <ul> -->
              <% @works.each do |work| %>
                  <div class="form-group">
                   <%= link_to work.title, work_path(work.id) %>
                  </div>
              <% end %>
          <!-- </ul> -->
          <% end %>
    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="workcontainer">
<h2 class="centerdiv">Add Work</h2>
<%= render :partial => 'form' %>
</div>

app/views/works/show.html.erb
<div class="workcontainer centerdiv">
  <div class="row" >
      <div class="col-6" id="main">
            <h2><%= @work.title %></h2>
            <p><%= @work.description %></p>
            <% unless @work.image.nil? %>
            <%= image_tag @work.image, :alt => @work.title %>
            <% end %>
      </div>
<!-- <div class="main"> -->


<!-- </div> -->
<div class="col-6" id="aside">

<!-- <div class="aside"> -->
  <h2>Designed By</h2>
      <% unless @user.nil? && @user.image.nil? %>
        <%= image_tag @user.image, :alt => @user.name, :id => "userdp" %>
      <% end %>
  <ul>
      <li>
        <label>Designer Name:</label>
        <%= label_tag @user.name %>
      </li>

      <li>
        <label>Date of Birth:</label>
        <%= label_tag @user.dob.strftime('%e %B, %Y') if @user.dob.present? %>
      </li>

      <li>
        <label>Address:</label>
        <%= label_tag @user.address %>
      </li>

      <li>
        <label>Phone:</label>
        <%= label_tag number_to_phone @user.phone %>
      </li>

      <li>
        <label>Company Name:</label>
        <%= label_tag @user.companyname %>
      </li>

      <li>
        <label>Company Address:</label>
        <%= label_tag @user.companyaddress %>
      </li>

      <li>
        <label>Company Website:</label>
        <%= label_tag @user.companywebsite %>
      </li>

      <li>
        <label>Company Contact:</label>
        <%= label_tag @user.companycontactinfo %>
      </li>
      <li>
        <label>Rating:</label>
        <% @avgrating.times do %>
        <label class="starselect">*</label>
        <% end %>
        <% if 5-@avgrating > 0 %>
        <% @rem = 5-@avgrating %>
        <% @rem.times do %>
        <label class="starremaining">*</label>
        <% end %>
        <% end %>
        <% if @ratanlytics.any? %>
        <table>
          <th>Overall Ratings</th>
            <% @ratanlytics.each do |key,value| %>
              <tr>
                    <td>
                       <%= pluralize value.to_i ,'person' %> rated for <%= key %>
                    </td>
              </tr>
            <% end %>
        </table>
        <% end %>

      </li>
      </ul>
    </div>
</div>
<div class="row">
  <div class="col-6">
    <div class="controls">
      <% if @current_user != nil && @current_user.id == @work.user_id %>
      <%= link_to 'Edit', edit_work_path(@work), :class => "btn btn-primary" %>
      <%= link_to 'Delete', @work, :method => 'delete', :class => "btn btn-primary" %>
      <% end %>
      <% if @current_user.present? %>
      <%= link_to 'Rate', new_ratework_path, :class => "btn btn-primary" %>
      <% end %>

      <% if @current_user != nil && @current_user.admin == "Buyer" %>
      <%= link_to 'Create Contract', new_contract_path, :class => "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>
</div>